### ISSUE TITLE
Cannot find my private repository

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2016-cw2#10]
> Submission will be via Github, so this time you'll need to actually work with your private repository. I have created you a private repository again, but this time it will be empty. 

However, I cannot find any private repository in HPCE folder. Could you please make a check?

**Comment by m8pple** [comment]
You still have a pending invitation request in github. There would have
been an invitation mail about 10 days ago.

Or if you go to:

https://github.com/HPCE

you should be able to accept it.

**Comment by lynx5120** [comment]
My bad. Thanks a lot.

**Comment by m8pple** [comment]
No worries. Enjoy!
