### ISSUE TITLE
TBB links

### ISSUE THREAD

**Issue by qc316** [HPCE/hpce-2016-cw2#13]
Hello,

I think the links referring to the tbb website should end with .html instead of .htm
For example, this [link](https://www.threadingbuildingblocks.org/docs/help/reference/algorithms/partitioners.htm) redirects to the home page whereas this [one](https://www.threadingbuildingblocks.org/docs/help/reference/algorithms/partitioners.html) shows the right information !

**Comment by m8pple** [comment]
Thanks - yes, you're right. It looks like they migrated over since I checked.
