### ISSUE TITLE
Some updates/amendments to readme.md

### ISSUE THREAD

**Issue by lloydabbott** [HPCE/hpce-2016-cw2#14]
Hello,

Here's a few things I think need updating/amending in the task:

- The section numbering is a bit mixed up, it's going 0,1,2,4,2,4,5,6,7,10 at the moment so I'm specifying which one of the section 4s I'm referring to below...

- In section **_4. Exploring the grain size of parallel_for_**, the first task is outlined, saying we should create a graph `results/direct_outer_versus_k.pdf`. Should it not be `results/direct_inner_versus_k.pdf` as we have parallelised the inner loop?

- Along with that in the first task, the bash commands specified there:
   ```
   export HPCE_DIRECT_INNER_K = <Whatever K you want>
   bin/time_fourier_transform hpce.direct_fourier_transform 0 30
   ```
should read
   ```
   bin/time_fourier_transform hpce.[your_login].direct_fourier_transform_parfor_inner 0 30
```
   as it does in _csv_and_pivot.md_, otherwise we are just running the original DFT with no dependency on K...

**Comment by m8pple** [comment]
Yes, you're right on all counts. Thanks!

I'll also need to update the list of graphs which should exist at the end.

**Comment by m8pple** [comment]
(I had the idea that markdown did section title numbering for some
reason, but that is lists).
