### ISSUE TITLE
git and private repo

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2016-cw2#15]
> I have followed your instructions here:
> https://github.com/HPCE/hpce-2016-cw2/blob/master/git.md, and I believe
> that overall I understand the concepts being explained and demonstrated.
> However, after getting "Everything up-to-date" messages in my Ubuntu terminal,
> after refreshing my private repo on github I still don't see anything. Is there an
> issue or am I doing something wrong?

**Comment by m8pple** [comment]
If you do:

    git remote -v

in your local repository, what is the output?

**Comment by jygoh1** [comment]
Managed to get it fixed with a forced push, thanks!

**Comment by m8pple** [comment]
Ok, good.

**Comment by pierreazalbert** [comment]
If I do `git remote -v` I get this: 

```
origin	https://github.com/HPCE/hpce-2016-cw2-pva13.git (fetch)
origin	https://github.com/HPCE/hpce-2016-cw2-pva13.git (push)
private	git@github.com:HPCE/hpce-2016-cw2-pva13 (fetch)
private	git@github.com:HPCE/hpce-2016-cw2-pva13 (push)
```
it that correct?

**Comment by m8pple** [comment]
Sorry, didn't notice the comment on the closed issue.

I think you've ended up with both of them pointing at the same repository. So
`origin` links to your private repo via `https`, but private uses `ssh`.

Ideally it would look like:

    origin  https://github.com/HPCE/hpce-2016-cw2.git (fetch)
    origin  https://github.com/HPCE/hpce-2016-cw2.git (push)
    private git@github.com:HPCE/hpce-2016-cw2-pva13.git (fetch)
    private git@github.com:HPCE/hpce-2016-cw2-pva13.git (push)

or:

    origin  https://github.com/HPCE/hpce-2016-cw2.git (fetch)
    origin  https://github.com/HPCE/hpce-2016-cw2.git (push)
    private https://github.com:HPCE/hpce-2016-cw2-pva13.git (fetch)
    private https://github.com:HPCE/hpce-2016-cw2-pva13.git (push)

So that origin points at my repository, but private points at your
repository.
