### ISSUE TITLE
Submission BB and test script missing

### ISSUE THREAD

**Issue by spr13** [HPCE/hpce-2016-cw2#17]
I finished the coursework and pushed everything on my private git repository.
I zipped the directory to upload it to black board but the upload link is missing from the assessment tab.
Are we getting a test script like the one we got for CW1?
Are the test scripts added on Fridays?
Thanks in advance.

**Comment by m8pple** [comment]
There is a note at the top of the readme about it. You should have received auto-test
information pushed directly into your private repo.

Specific to @spr13 - it looks like you haven't actually pushed the stuff up. I can't see
anything in the repo.

**Comment by spr13** [comment]
Apparently git rejected my push request. So I did the pull first like the hint told me to, but still it won't let me push. Not sure what I should try next.
Any advice would be appreciated.

```
santiago@ubuntu:~/Documents/HPCE/CW2/hpce-2016-cw2-spr13$ git pull origin master 
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (9/9), done.
remote: Total 15 (delta 10), reused 11 (delta 6), pack-reused 0
Unpacking objects: 100% (15/15), done.
From https://github.com/HPCE/hpce-2016-cw2
 * branch            master     -> FETCH_HEAD
   ba140eb..97fb9eb  master     -> origin/master
Updating ba140eb..97fb9eb
Fast-forward
 git.md    | 76 +++++++++++++++++++++++++++++++--------------------------------
 readme.md | 47 +++++++++++++++++++++++++++++----------
 2 files changed, 73 insertions(+), 50 deletions(-)
santiago@ubuntu:~/Documents/HPCE/CW2/hpce-2016-cw2-spr13$ git push -u private master
Username for 'https://github.com': spr13
Password for 'https://spr13@github.com': 
To https://github.com/HPCE/hpce-2016-cw2-spr13.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/HPCE/hpce-2016-cw2-spr13.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.
santiago@ubuntu:~/Documents/HPCE/CW2/hpce-2016-cw2-spr13$ 

```

**Comment by m8pple** [comment]
In the interests of expediency, what I would suggest is:

1. Clone another local copy of your repository (while keeping all the work
   you have done in your existing local repo). This new local repository
   will not contain your additions, but will be in sync with your remote
   private repository.

2. Copy all of your modified files from your old repository to the new 
    repository. If you're feeling lazy you can just copy everything but the
    `.git` folder over.

3. Perform an add/commit in the new repository, which will capture all the new documents
   and changed documents as one commit.

4. Push from the new local repository up to the remote private repository.

At this point the new local repo should be back in sync. (Hold onto your old
local repo till you are happy this has happened). You'll lose your true history
of commits, but it will get your work into the private repo so you can
forget about it.

This is not really the correct way of doing things - looking at the debug
output I'm wondering about the `master` vs `origin\master` but I'm
not expert enough in git that I can confidently do remote debug (someone else
may know?) 

As to why it happened: I suspect you had two local repositories at some
point, or you had a combination of a repository pulled from the master
and a different version in your repo. 

Sorry, a bit wishy-washy - I'd need to look at it interactively to work
out exactly what happened.

**Comment by spr13** [comment]
Thank you,
That was very helpful. I did exactly like you said and it worked.
