### ISSUE TITLE
parallel FFT and chunking

### ISSUE THREAD

**Issue by m8pple** [HPCE/hpce-2016-cw2#18]
> In the first part of parallelising the FFT, I don't get what you ask of us to implement chunking
> without doing any parallelisation. Is chunking not a form of parallelisation by itself?
> In addition to this conceptual question, does it mean that I should still loop j
> from 0 to m-1 and simply replace w by std::pow(wn,j)? If instead we're supposed to
> use the chunks, your tips in 
>  
>    4. Exploring the grain size of parallel_for
> 
> state that when using chunks, you can either execute it directly or in parallel
> with chunk size K. Or is it that even when executing it directly, because I
> have defined my "range" to have a starting point i, ending point j and
> chunk size K, it already executes it in chunks?

**Comment by m8pple** [comment]
I'm assuming you mean this sentence:

> First apply the loop transformation described above, without introducing any parallelism,
> and check it  works with various values of K, via the environment variable HPCE_FFT_LOOP_K.

In this case I mean that you should apply the chunking code transform, such that there
is an outer loop which steps forwards by chunks, and an inner loop which does the
chunk. So for an original loop that looks like this:

    x=init();
    for(int i=0; i<N; i++){
        x=step(x);
    }

turn it into a loop that looks like this:

    for(int o=0; o<N; o+=K){
        x=jump_to(o);
        for(i=0; i<o+K; i++){
             x=step(x);
        }
    }

The reason I suggest doing the chunking without parallelism is so that you can test it
more easily, and debug it. For example, a useful test to work out if it actually
still does the same thing would be to reverse the outer loop:

    for(int o=N-K; o>=0; o-=K){
        x=jump(o);
        for(i=0; i<o+K; i++){
             x=step(x);
        }
    }

(ignoring some cases where N is not a multiple of K).

The point is that you have an outer loop which can now execute in 
any order (and so can be parallelised), with an inner loop which is
still sequential and uses `step` (cheap) rather than `jump` (expensive).

**Comment by jygoh1** [comment]
Thanks! In your next step, you say "Once you have got it working with a non parallel chunked loop, replace the outer loop with a parallel_for loop using simple_partitioner, and check that it still works for different values of HPCE_FFT_LOOP_K." However, the parallel_for already does some chunking, so how would I incorporate both nested loops here? From what I can tell, this seems to replace both loops entirely.

**Comment by m8pple** [comment]
So if you were to replace the previous pseudo-code with this:

    parallel_for( blocked_range(0, n, K), []()( blocked_range &range){
        x=jump(range.begin());
        for(i=range.begin(); i<range.end(); i++){
             x=step(x);
        }
    });

Then you have chunking and parallelism. simple-partitioner means you
control the minimum and maximum chunk size yourself.

**Comment by m8pple** [comment]
> For parallelising the FFT with chunks, I have implemented your algorithm, yet it still fails the test. My > code is as shown:

    parallel_for( blocked_range(0, n, K), []()( blocked_range &range){
        x=jump(range.begin());
        for(i=range.begin(); i<range.end(); i++){
             // x=jump(range.begin());
             f(x);
             x=step(x);
        }
    });

> The commented out part is to use std::pow at each step (i.e. more costly), but when I use that instead > of using std::pow once every chunk and doing w=w*wn within the chunk, the tests all pass (shown
> below).

    parallel_for( blocked_range(0, n, K), []()( blocked_range &range){
        x=jump(range.begin());
        for(i=range.begin(); i<range.end(); i++){
             x=jump(range.begin());  
             f(x);
             //x=step(x);
        }
    });

> My tests initially failed if I used w=std::pow(wn,j) i.e. not casting to int, so I thought it was a
> cast issue and tried similar methods for the line outside the FOR loop, but still wasn't able
> to fix the issue. Am I doing something fundamentally wrong?

**Comment by m8pple** [comment]
Think carefully about x:
- Where is it declared in relation to the parallel loop (inside or outside)?
- How is it captured by the lambda (reference or value)?
- Who is it shared with?

**Comment by jygoh1** [comment]
got it! realised my small but important error. just a random question, i noticed that there's a Raymond Williams (https://github.com/raymond-williams) making commits to my personal repo, but am not competent enough in git to know exactly what he's doing and more importantly the impact of what he's doing/did. Is that a known issue?

**Comment by m8pple** [comment]
Ray was a student last year (he was at the EESoC event this year on behalf of ARM).

He made some pull request to the coursework, so they are intertwined with mine.
