### ISSUE TITLE
Mistake in specifications: Decimal integer

### ISSUE THREAD

**Issue by pm1113** [HPCE/hpce-2016-cw2#20]
Hello, 

I believe there might be a typo in the specification. 

Modify your implementation of direct_fourier_transform_parfor_inner to use a chunk size K, where K is either specified as a _**decimal integer**_ using the environment variable HPCE_DIRECT_INNER_K, or if it is not set, you should use a sensible default.

Should it be integer?

Thanks.

**Comment by m8pple** [comment]
I think it's ok (?)

As an alternative, we could have:

- hexadecimal integer : `0xFF`
- decimal float: `6.7`

And for completeness:

- hexadecimal float : 0xC.56

**Comment by pm1113** [comment]
Awesome. I get it now.

Thanks so much!

**Comment by m8pple** [comment]
No problem.
