### ISSUE TITLE
Typo in readme.md section 5?

### ISSUE THREAD

**Issue by JHertz5** [HPCE/hpce-2016-cw2#21]
Hi

I'm at the end of section 5, under the sub-heading "Use tbb::task_group to parallelise the recursion", and the document says to look for a section of code in our version of fast_fourier_transform.cpp that matches: 
```
forwards_impl(m,wn*wn,pIn,2*sIn,pOut,sOut);
forwards_impl(m,wn*wn,pIn+sIn,2*sIn,pOut+sOut*m,sOut);
```
As far as I can tell, this does not exist in fast_fourier_transform.cpp in my private repository or the main repository, and there are too many inputs to work with `forwards_impl()` anyway. I assume that this part of the document is supposed to read:
```
recurse(m,wn*wn,pIn,2*sIn,pOut,sOut);
recurse(m,wn*wn,pIn+sIn,2*sIn,pOut+sOut*m,sOut);
```
, which does exist in the code. Is that correct?

**Comment by m8pple** [comment]
Yes, you're right, thanks.

I simplified the code a bit for this year, and it looks like I overlooked that
when checking it (it is difficult not to do it on auto-pilot, rather than
following the instructions).
