### ISSUE TITLE
Two instances of the same graph

### ISSUE THREAD

**Issue by Szypicyn** [HPCE/hpce-2016-cw2#22]
Good day,

At the bottom, it is being requested that we submit 6 pdfs. Two of them seem to repeat, though it is explicitly stated that there should be 6 graphs:

"There are quite a few graphs to get (six), but if you follow the advice about how to automate things, it is fairly quick to get them."

The ones that repeat are:
results/direct_outer_strong_scaling.pdf
results/direct_outer_strong_scaling.pdf

The readme.md only has 5 tasks. Should there be an extra graph?

Thanks.

**Comment by m8pple** [comment]
Nope, no extra graph - you're right.

I think I didn't catch it because my test-bench actually checks for the existence
of the same graph twice, as I copied it from that summary.

Thanks!
