### ISSUE TITLE
5 Using tbb::task_group in fast_fourier_transform

### ISSUE THREAD

**Issue by lynx5120** [HPCE/hpce-2016-cw2#24]
I'm confused of the section [Use tbb::task_group to parallelise the recursion](https://github.com/HPCE/hpce-2016-cw2#use-tbbtask_group-to-parallelise-the-recursion). Instruction said:

> Modify the code to use tbb::task_group to turn the two calls into child tasks.

If I simply replace original 2 lines with `group.run( [&](){ recurse(...) } );`, and it runs for 2 times, will 4 tasks (splitted by 2 tasks) be in the same task group? I mean:

```
       4
     /    \
   2      2
 /   \    /   \
1     1    1    1
```

Four "1"s will be in the same task group? Or the first two in one group, and the latter two in another group?  

As for [6. Adjustable grain size for the FFT](https://github.com/HPCE/hpce-2016-cw2#6-adjustable-grain-size-for-the-fft), I tried to add a member to the class to record group size. But recurse() is a const function and it is not able to change that member. Any hint about how to record group size?

**Comment by jeremych1000** [comment]
If I understand task groups correctly (please correct if wrong), it is
      4               <- if you stop here there are 4 tasks in one group
     /    \
   2      2           <- if you stop here there are 2 tasks in 2 groups
 /   \    /   \
1     1    1    1   <- if you stop here there are 1 task in 4 groups

W.r.t. recording group size, try a static variable. You can modify it every time you recurse.

**Comment by m8pple** [comment]
Noo! Don't use a static variable - remember that will be shared amongst all tasks.

Have you looked at this issue:
https://github.com/HPCE/hpce-2016-cw2/issues/18

**Comment by jeremych1000** [comment]
Welp, time to change my code then.

**Comment by lynx5120** [comment]
Uh....Seems like I misunderstood the meaning of K. Thanks. However, I just finish section 5 & 6. When I try section 7:

> First apply the loop transformation described above, without introducing any parallelism, and check it works with various values of K, via the environment variable HPCE_FFT_LOOP_K.

And terminal runs `time_fourier_tranform` well before arg n <= 64. After  n> 64, it just tells me `Segmentation fault (core dumped)`. No matter which K I choose.

My code is like this:

`if(m>K){
   for(int o=0; o<m; o+=K){
      x=jump(o);
      for(int i=o; i<o+K; i++){
         x=step(x);
      }
   }
}  
else{
  for(int i=0; i<m; i++){
     x=step(x);
  }
}`

Have no idea if I'm wrong about anything.

**Comment by lynx5120** [comment]
Uh, I was right on the upper code, it's just I use the wrong way to get K.

Anyway, really learned a lot from this coursework. Thank you very much!

**Comment by m8pple** [comment]
Glad you got it fixed.
