### ISSUE TITLE
"Could not read from remote repository" when pushing to private master

### ISSUE THREAD

**Issue by hfroot** [HPCE/hpce-2016-cw2#25]
When I follow the below instructions to set up the remote repo I get the error: "Permission denied (publickey). fatal: Could not read from remote repository."

 - cloning the public repo
 - move into the new directory
 - git remote add private git@github.com:HPCE/hpce-2016-cw2-hr1013.git
 - git push -u private master

However, when I replace git@github.com:HPCE/hpce-2016-cw2-hr1013.git with https://github.com/HPCE/hpce-2016-cw2-hr1013.git everything works. What happened and do I need to change the repo setup?

**Comment by majpoynton** [comment]
Same thing happens with me - I assumed it was just outdated.

**Comment by m8pple** [comment]
You can use ssh or https, but ssh requires a little authentication setup:

  https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/

So either method is fine, but one requires typing in the password all the time.

**Comment by eugenius1** [comment]
https doesn't have to mean re-entering your password every time, see [Caching your GitHub password in Git](https://help.github.com/articles/caching-your-github-password-in-git/).
