### ISSUE TITLE
4. Using tbb::parallel_for in direct_fourier_transform properly - TS clarification

### ISSUE THREAD

**Issue by majpoynton** [HPCE/hpce-2016-cw2#26]
> T_S = Time taken for sequential version

Is this on 1 core or 4? From what I understand, it should make no difference because there is no loop parallelism in the sequential version. However, some of the code presumably _can_ be executed in parallel (I hope that's right - demonstrably 8 cores are better than 1, and I can't believe it's just whenever a programmer has decided to use tbb - so I guess it must do some parallelism automatically), just not the loops so we should use 1 core. And we're just testing the loop, so therefore to remove any bias, we should use 1 core. However again, since we're asked to run the tbb implementation with 1,2,3,4, won't there be a bias towards 4, outside the fact that the loop is parallelised?

In a way, I suppose it doesn't matter, since everything's relative, there'll just be an absolute offset in the scaling.

This is less an issue with the spec and more just a question.
Thanks

**Comment by m8pple** [comment]
8 cores are only better than 1 if some part of the code is made parallel. Whenever an
application appears faster with more cores, there is at least some part of it that is
creating more processes or threads in some way.

So your sequential version should be truly sequential - no C++ compiler that I am aware
of will routinely create extra threads (they exist, but require special flags or instructions).
