### ISSUE TITLE
bad_alloc on AWS

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw2#27]
**Environment**: WSL -> ssh into AWS

**Command run**: task 8 script

**Expected**: runs all tests without problems

**Actual**: Caught exception: std::bad_alloc

Any ideas what is causing this? Does my EC2 instance not have enough RAM? Is the process not terminating properly?

Interesting enough if I look at my csv data dump everything seems normal...I have all my needed values...

```
Running test for HPCE_FFT_RECURSION_K = 1; HPCE_FFT_LOOP_K = 4...
# 1, 4,  name, allowedP, trueP, n, [sentinel], time
Running test for HPCE_FFT_RECURSION_K = 1; HPCE_FFT_LOOP_K = 8...
# 1, 8,  name, allowedP, trueP, n, [sentinel], time
Caught exception: std::bad_alloc
Running test for HPCE_FFT_RECURSION_K = 1; HPCE_FFT_LOOP_K = 16...
# 1, 16,  name, allowedP, trueP, n, [sentinel], time
Caught exception: std::bad_alloc
<...>
```

**Comment by m8pple** [comment]
It usually means that you have run out of storage, e.g. you are allocating things
without freeing them, or have asked to allocate something that is much bigger
than could be allocated.

It can also be todo with memory corruption within the process.

**Comment by jeremych1000** [comment]
Not submission-gating - close if necessary.

**Comment by m8pple** [comment]
Ok - maybe I'll look at it in more detail sometime when I have an AWS instance spun up.
