### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by gloriagegao** [HPCE/hpce-2016-cw2#30]
I got the following error on compiling after replacing the simple parallel_for with the parallel_for with chunk K.

/usr/include/c++/5/ext/new_allocator.h:120:4: error: invalid new-expression of abstract class type ‘hpce::gg813::direct_fourier_transform_parfor_inner’
  { ::new((void *)__p) _Up(std::forward<_Args>(__args)...); }

which points to this file /usr/include/c++/5/ext/new_allocator.h which I don't think I have ever changed and I even couldn't find it in the suggested path. 

How to understand and eliminate this error?

**Comment by m8pple** [comment]
Generally this message means that you have created a class which has some
virtual members which are not specified. In this case, that would mean that
there is some function inherited from `fourier_transform` which is not
implemented.

This shouldn't have happened if you copied the class over and just replaced
the function bodies, and particularly if you previously had `parallel_for` working
without chunking.

Have you changed anything else - in particular, have you changed any of
the parameter types of `forwards_impl` or `backwards_impl`. Also, is this
the only error message? Are there any other messages about functions not
being implemented?

Your repository is empty, so I can't really comment on the code.

**Comment by gloriagegao** [comment]
The parallel_for works all the way until this point and this is the only error. I did change the looping variable data type from size_t to unsigned so that in the previous task it doesn't complain about data type.

**Comment by gloriagegao** [comment]
The code is now in my private repository.

**Comment by gloriagegao** [comment]
I got it! I declared K in the wrong place.
