### ISSUE TITLE
Can build time_fourier_transform, FAIL | Can build test_fourier_transform, FAIL

### ISSUE THREAD

**Issue by andreamifsud** [HPCE/hpce-2016-cw2#32]
When I checked the log files in the auto test, there are the following tests which fail:

> 12, Can build test_fourier_transform, FAIL
> 13, Can build time_fourier_transform, FAIL

On my laptop, these build successfully. Why aren't these building?
Hence as time_fourier_transform does not build, these also fail:

> 14, Checking test_fourier_transform still lists 'hpce.direct_fourier_transform', FAIL
> 15, Checking test_fourier_transform still lists 'hpce.fast_fourier_transform', FAIL
> 16, Checking test_fourier_transform now lists 'hpce.am6416.direct_fourier_transform_parfor_inner', FAIL
> 17, Checking test_fourier_transform now lists 'hpce.am6416.direct_fourier_transform_parfor_outer', FAIL
> 18, Checking test_fourier_transform now lists 'hpce.am6416.fast_fourier_transform_parfor', FAIL
> 19, Checking test_fourier_transform now lists 'hpce.am6416.fast_fourier_transform_taskgroup', FAIL
> 20, Checking test_fourier_transform now lists 'hpce.am6416.fast_fourier_transform_combined', FAIL

Thanks

**Comment by jeremych1000** [comment]
Post your makefile and /src/ folder structure.

**Comment by m8pple** [comment]
@andreamifsud It looks like you worked this out, as the last build compiled, but in
case others are wondering:
- You can see the build command listed in the main log
- The actual compilation error messages are available in the logs/build_*.log files

In this case it was a missing function.
