### ISSUE TITLE
Test #39

### ISSUE THREAD

**Issue by Filippo555** [HPCE/hpce-2016-cw2#37]
I am having some trouble with test 39. As far as I understood, the combined version should be faster than both task_group and parfor, however the test quotes: 

`check time for taskgroup (...) is no more than 0.9x that of combined (...)`

I have discussed this with two other students, and there even seems to be conflicting results for this test, as someone passes it with combined > task_group and someone else passes it with task_group > combined (in both cases the times are almost identical)

Could you please clarify what is expected of combined and if indeed it is supposed to be slower than task_group?

Something similar came up in issue #34 as commented by @jeremych100

**Comment by m8pple** [comment]
It's related to this section for #23:

> Between the taskgroup and the parfor techniques, you'll generally find
> the taskgroup is much more effective. So your combined version should
> be aiming to get a good speed-up for large n, but avoid any slow-down
> for medium/small n. You may want to revisit your default tuning parameters
> for combined, esp. for the parfor bit.

(In the following, pretend that 1/0.9 ~= 1.1)

So this relationship  `taskgroup <= 0.9 * combined`, or `taskgroup * 1.1 <= combined`
is trying to check that the addition of the parfor section hasn't slowed down the
taskgroup version.

Ideally what you'd see for the times is:
- taskgroup == combined : for small/medium n
- taskgroup > combined : for large n

In the zone of `n` I'm testing (medium-size, for execution time reasons), I'd expect the first case,
so they should be the same. However, due to noise, there needs to be some slack
in the condition.

So saying checking `taskgroup * 1.1 <= combined` is making sure that combined is
at least no worse than taskgroup.

I could have more strictly used:

    taskgroup * 0.9 <= combined <= 1.1 * taskgroup

in order to check both sides, but the more likely situation is that people accidentally
slow combined down.

**Comment by Filippo555** [comment]
Thanks now it's clearer. Essentially we are expecting "combined" to preform similarly to "taskgroup", with some wiggle room in both directions. The way you worded it was slightly confusing because 

`check time for taskgroup is no more than 0.9x that of combined `

essentially says that "taskgroup" should take up at most 90% of the time "combined" takes (hence taskgroup should be faster), while in the experiment we are designing "combine" to be faster than "taskgroup". 

If your actual scripts checks that combined performs within range of taskgroup, then it makes perfect sense. And it also explains why two other students where both passing the test with their own "combined" being respectively slightly faster and slightly slower than taskgroup. 

Thank you!

**Comment by jeremych1000** [comment]
Thanks - I've since re-run the tests and modified some parameters.

**Comment by Filippo555** [comment]
By the way, I previously did not include my times because when the test was run yesterday I had an error in the code which leaded to very slow execution. But looking at it I just realized that I had passed the test despite "combined" being much slower than "taskgroup". Here it is for reference: 

`check time for taskgroup (0.4617942240) is no more than 0.9x that of combined (2.7948070500)., PASS`

At this point I am no longer sure I understood m8pple's comment since combined for me was much slower than taskgroup but still passed the test.

**Comment by jeremych1000** [comment]
>  So saying checking taskgroup * 1.1 <= combined is making sure that combined is
at least no worse than taskgroup.

Other way right? 

I've just modified some parameters and re-ran the test for n=2^22 and I get combined = 0.48629, taskgroup = 0.45625.

So this fulfills
> taskgroup * 0.9 <= combined <= 1.1 * taskgroup

but not
>  taskgroup * 1.1 <= combined

However given @Filippo555 's recent test I'm not sure whether I should be expecting a FAIL or a PASS. @m8pple do you mind double-checking your script for test 39 to make sure then comparisons are giving the correct PASS/FAIL? There is no test39.log in /dt10_logs/.

**Comment by m8pple** [comment]
Ok, maybe I've got the condition the wrong way round.

The actual test in the actual script is (can't easily use non-integer maths):

    "9 MULT $timing_fast_taskgroup < 10 MULT $timing_fast_combined"

which is the same as:

    0.9 * taskgroup < combined

Oops. So I had the condition the wrong way round. So if the times are
about the same size then it works - that was true of all the ones I
looked at, so I thought it was correct.

So what I _meant_ to say is:

    taskgroup * 1.1 < combined

It doesn't help that in my comment above I managed to transpose them as well.

I think I'll just delete that test...

**Comment by m8pple** [comment]
Sigh - the thing above doesn't even look correct:

    taskgroup * 1.1 < combined

?

The full statement of what I wanted to express is:

    taskgroup / (1 + eps) < combined < taskgroup * (1 + eps)

for a value of eps that is sufficient to tolerate noise, but had to go through
these hoops due to integer maths.

Definitely deleting that test.
