### ISSUE TITLE
Plotting individual n values on Excel

### ISSUE THREAD

**Issue by jeremych1000** [HPCE/hpce-2016-cw2#38]
ref #19 @nar213 @m8pple 

Was trying to plot individual n values using Pivot Charts but there doesn't seem to be an option to do so. Anyone know where I can do that?

Below is the Excel dialog window for the settings for Time (s).

![image](https://cloud.githubusercontent.com/assets/17688104/19858541/c57b6558-9f79-11e6-8713-1c8d34a0cbea.png)

**Comment by m8pple** [comment]
Using this data:

![image](https://cloud.githubusercontent.com/assets/3024705/19862523/a1b77274-9f88-11e6-8718-028c323e01d2.png)

I get this default pivot-chart:

![image](https://cloud.githubusercontent.com/assets/3024705/19862534/b0395326-9f88-11e6-9b42-395da01ec54c.png)

To select a specific n you can add it as a filter item:

![image](https://cloud.githubusercontent.com/assets/3024705/19862564/cdb58af0-9f88-11e6-8449-7e5545c8e73c.png)

Then click on the little arrow next to n:

![image](https://cloud.githubusercontent.com/assets/3024705/19862604/f44a41a6-9f88-11e6-91fd-fd32c4780964.png)

And choose the value of n you want:

![image](https://cloud.githubusercontent.com/assets/3024705/19862629/0ff3bcb6-9f89-11e6-8143-406aa7d5a34d.png)

You could also turn it into a line-chart, then select multiple (notice I've
flipped the fields a bit). Here I've selected
n=2 and n=4:

![image](https://cloud.githubusercontent.com/assets/3024705/19862682/3edc31f2-9f89-11e6-981e-95963cd5258b.png)

**Comment by jeremych1000** [comment]
Ah sorry I meant to say plot individual time values for all n. In your last screenshot you have Sum of Time (s) too.

**Comment by m8pple** [comment]
Oh, I should have said - it's showing sum of T, but there is only one thing in the sum.

If I change it to count of T:

![image](https://cloud.githubusercontent.com/assets/3024705/19864980/5e5d0494-9f92-11e6-938e-3de9a5bfc86b.png)

Then there is only one thing in each line:

![image](https://cloud.githubusercontent.com/assets/3024705/19865000/6bcfbce8-9f92-11e6-9449-727050d8872e.png)

Switching to count is often a good way of working out whether you have filtered and projected
down to single data-points, then move back to sum.

**Comment by jeremych1000** [comment]
Good point, thanks.

Closed.
